version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./dist:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
    php:
        image: php:7-fpm-alpine
        volumes:
            - ./dist:/usr/share/nginx/html
            - ./php-log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
